### ISSUE TITLE
Unable to log failing tests

### ISSUE THREAD

**Issue by jbadeau** [reportportal/agent-net-gauge#14] opened 2019-10-10 14:55 UTC
The plugin is not able send to reportportal when a scenario fails.

Unhandled Exception: System.NullReferenceException: Object reference not set to an instance of an object.
   at ReportPortal.Gauge.Program.Main(String[] args) in C:\projects\agent-net-gauge\ReportPortal.Gauge\Program.cs:line 131
Successfully generated html-report to => C:\Daten\git\delimac-test\e2e\reports\html-report\index.html
Specifications:	1 executed	0 passed	1 failed	0 skipped
Scenarios:	2 executed	1 passed	1 failed	0 skipped

**Comment by nvborisenko** [comment] 2019-10-10 18:08
@jbadeau what version of plugin you use? The latest preview?

**Comment by jbadeau** [comment] 2019-10-10 18:09
Yes the latest.

**Comment by nvborisenko** [comment] 2019-10-10 18:26
Please verify in 1.1.0-preview.4. Actually I didn't test it. Fill free to reopen the issue.

**Comment by jbadeau** [comment] 2019-10-11 09:15
Hi same error

Unhandled Exception: System.NullReferenceException: Object reference not set to an instance of an object.
   at ReportPortal.Gauge.Program.Main(String[] args) in C:\projects\agent-net-gauge\ReportPortal.Gauge\Program.cs:line 131
Successfully generated html-report to => C:\Daten\git\delimac-test\api\reports\html-report\index.html
Specifications:	1 executed	0 passed	1 failed	0 skipped
Scenarios:	10 executed	0 passed	10 failed	0 skipped

**Comment by nvborisenko** [comment] 2019-10-11 10:49
@jbadeau actually I cannot reproduce the issue. Could you please provide sample test project? Thx.

**Comment by iminder-singh** [comment] 2019-12-10 13:53
Hi @nvborisenko, I'm also trying to use this plugin and I'm seeing the above null reference exception for failing tests. Have you been able to look at this? What data/info do you require to help debug? Thanks.

**Comment by nvborisenko** [comment] 2019-12-17 11:59
@IRE04 since I cannot reproduce the issue, please provide super simple test project which I can execute and see whether issue is reproducible.

**Comment by nvborisenko** [comment] 2019-12-19 13:22
@jbadeau @IRE04 please try 1.0.0-preview.5 version. This version doesn't have fix, but introduces possibility to get more details about the issue.

- add 'rp_log_enabled = true' to your config
- please provide exact exception message from console

**Comment by jbadeau** [comment] 2019-12-19 14:12
sure

**Comment by jbadeau** [comment] 2019-12-19 14:22
Unhandled exception.
System.InvalidOperationException: Wire Type is invalid.
at Google.Protobuf.UnknownFieldSet.MergeFieldFrom(CodedInputStream input)
at Google.Protobuf.UnknownFieldSet.MergeFieldFrom(UnknownFieldSet unknownFields, CodedInputStream input)
at Gauge.Messages.Message.MergeFrom(CodedInputStream input)
at Google.Protobuf.MessageExtensions.MergeFrom(IMessage message, Byte[] data, Boolean discardUnknownFields)
at Google.Protobuf.MessageParser`1.ParseFrom(Byte[] data)
at ReportPortal.Gauge.Program.Main(String[] args)
Unable to connect to plugin ReportPortal 1.1.0. [Warning] Failed to send message to plugin: reportportal  write tcp 127.0.0.1:53836->127.0.0.1:53841: wsasend: An existing connection was forcibly closed by the remote host.

**Comment by jbadeau** [comment] 2019-12-19 14:22
By the way. We recently migrated to v5 so might be another issue now

**Comment by nvborisenko** [comment] 2019-12-19 14:57
@jbadeau Again I would ask to create a simple project with few dummy tests to reproduce the issue on my machine. It will allow us to fix the issue quickly. Please do it.

**Comment by jbadeau** [comment] 2019-12-20 15:54
I have created a new "Java" gauge project using the latest version of the vscode gauge plugin.
Adding the latest reportportal plugin cause various errors with the RP v5

**Comment by nvborisenko** [comment] 2019-12-21 16:23
@jbadeau I was able to reproduce your issue on my workstation. v5 is not a reason. The issue is not reproducible if I use some combination of gauge core/runner/plugin version.

The reason of the issue that all gauge components, which are communicating with each others, are not synchronized.

I raised this issue to gauge team https://github.com/getgauge/gauge-csharp-core/issues/1

Let's wait a response from gauge.

**Comment by jbadeau** [comment] 2019-12-26 10:18
ok

**Comment by iminder-singh** [comment] 2020-01-10 12:14
@nvborisenko Thanks for looking into this - I've followed the issue you raised with gauge - is there any resolution/fix to this problem ?

**Comment by vasanthsdet** [comment] 2020-01-20 06:48
@jbadeau I am also facing the issue after installing V5, is there any resolution for this issue..
Unhandled exception.
System.NullReferenceException: Object reference not set to an instance of an object.
at ReportPortal.Gauge.Program.Main(String[] args)
Plugin [ReportPortal] with pid [5107] did not exit after 4.00 seconds. Forcefully killing it.
Specifications:	1 executed	0 passed	1 failed	0 skipped
Scenarios:	1 executed	0 passed	1 failed	0 skipped

**Comment by nvborisenko** [comment] 2020-01-20 19:53
@vasanthdama java runner too?

**Comment by jbadeau** [comment] 2020-01-22 00:25
I will rewrite this plugins as I don’t have time to wait and there is no issues with my current java based plugins.

**Comment by nvborisenko** [comment] 2020-02-20 18:04
Fixed in v1.1.0

**Closed as completed by nvborisenko** 2020-02-20 18:04 UTC
